import { MovieRating } from './movie-rating';
export class Movie {
    public Title: string;
    public imdbID: string;
    public Poster: string;
    public Type: string;
    public Year: number;
    public Rated: string;
    public Released: Date;
    public Runtime: string;
    public Genre: string;
    public Director: string;
    public Writer: string;
    public Actors: string;
    public Plot: string;
    public Language: string;
    public Country: string;
    public Awards: string;
    public Metascore: string;
    public imdbRating: number;
    public imdbVotes: number;
    public DVD: string;
    public BoxOffice: string;
    public Production: string;
    public Website: string;
    public Response: boolean;
    public Ratings: Array<MovieRating>;
    constructor({ title, imdbid, poster, type, year, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, metascore, imdbrating, imdbvotes, dvd, boxoffice, production, website, response, ratings }: { title: string; imdbid: string; poster: string; type: string; year: number; rated: string; released: string; runtime: string; genre: string; director: string; writer: string; actors: string; plot: string; language: string; country: string; awards: string; metascore: string; imdbrating: number; imdbvotes: number; dvd: string; boxoffice: string; production: string; website: string; response: string; ratings: Array<MovieRating>; }) {
        this.Title = title ?? '';
        this.imdbID = imdbid ?? '';
        this.Poster = poster ?? 'Default.jpg';
        this.Type = type ?? '';
        this.Year = year ?? 0;
        this.Rated = rated ?? '';
        this.Released = released !== undefined ? new Date(released) : new Date();
        this.Runtime = runtime ?? '';
        this.Genre = genre ?? '';
        this.Director = director ?? '';
        this.Writer = writer ?? '';
        this.Actors = actors ?? '';
        this.Plot = plot ?? '';
        this.Language = language ?? '';
        this.Country = country ?? '';
        this.Awards = awards ?? '';
        this.Metascore = metascore ?? '';
        this.imdbRating = imdbrating ?? 0;
        this.imdbVotes = imdbvotes ?? 0;
        this.DVD = dvd ?? '';
        this.BoxOffice = boxoffice ?? '';
        this.Production = production ?? '';
        this.Website = website ?? '';
        this.Response = response !== undefined ? (response === 'true') : false;
        this.Ratings = ratings ?? new Array<MovieRating>();
    }
}
